#!/bin/bash
#PBS -N gs_2Proc
#PBS -l select=1:ncpus=2:mpiprocs=2:mem=2gb:interconnect=mx
#PBS -l walltime=00:10:00
#PBS -j oe

source /etc/profile.d/modules.sh

module purge
#module add gcc/4.8.1
#module add openmpi/1.8.4
#module add fftw/3.3.3-dp-gcc-ompi
module add gcc/4.4 mpich2/1.4

NCORES=`qstat -xf $PBS_JOBID|grep List.ncpus|sed 's/^.\{26\}//'`

cd $PBS_O_WORKDIR

mpiexec -n $NCORES ./runmain -i outfile.dat
