#!/bin/bash
#PBS -N hw10
#PBS -l select=2:ncpus=8:mpiprocs=8:mem=4gb:interconnect=mx
#PBS -l walltime=00:40:00
#PBS -j oe

source /etc/profile.d/modules.sh
module purge

module add gcc/4.8.1
module add openmpi/1.8.4
module add fftw/3.3.3-dp-gcc-ompi

#module add gcc/4.4
#module add mpich2/1.4

NCORES=`qstat -xf $PBS_JOBID|grep List.ncpus|sed 's/^.\{26\}//'`
cd $PBS_O_WORKDIR
mpiexec -n $NCORES ./deodhar_shreya_hw10fin
